ifeq ($(subdir),string)
sysdep_routines += \
  memcmp_generic \
  memcmp_kunpeng950 \
  memcpy_a64fx \
  memcpy_generic \
  memcpy_kunpeng950 \
  memcpy_mops \
  memcpy_oryon1 \
  memcpy_sve \
  memmove_mops \
  memset_a64fx \
  memset_generic \
  memset_kunpeng \
  memset_mops \
  memset_oryon1 \
  memset_sve_zva64 \
  memset_zva64 \
  strlen_asimd \
  strlen_generic \
  # sysdep_routines
endif # ifeq ($(subdir),string)

ifeq ($(subdir),malloc)
sysdep_routines += \
  malloc-ifuncs \
  # sysdep_routines
endif # ifeq ($(subdir),malloc)
