static dlmopen_test_spec dltest[] =
  {
   {
    .name = "dlmopen-unique:0:none--ns0",
    .desc = "dlmopen a DF_GNU_1_UNIQUE dso into ns0",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_BASE,
    .handle_ns = 0,
    .handle_type = DSO,
    .preloaded = { },
    .loaded = { [0] = DSO|NEW },
   },
   {
    .name = "dlmopen-unique:0:ns0--ns0",
    .desc = "dlmopen a DF_GNU_1_UNIQUE dso into ns0 while already present",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_BASE,
    .handle_ns = 0,
    .handle_type = DSO,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO },
   },
   {
    .name = "dlmopen-unique-shared:0:ns0--ns0",
    .desc = "dlmopen RTLD_SHARED a DF_GNU_1_UNIQUE dso into ns0 while already present",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_BASE,
    .args.flags = RTLD_SHARED,
    .handle_ns = 0,
    .handle_type = DSO,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO },
   },
   {
    .name = "dlmopen-unique:X:ns0--nsX",
    .desc = "dlmopen a DF_GNU_1_UNIQUE dso into nsX while present in ns0",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_NEWLM,
    .handle_ns = EXPECTED_NS,
    .handle_type = PROXY,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO, [EXPECTED_NS] = PROXY|NEW },
   },
   {
    .name = "dlmopen-unique:0:ns0-nsXp--ns0--nsXp",
    .desc = "dlmopen a DF_GNU_1_UNIQUE dso already in ns0 proxied in nsX",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_BASE,
    .handle_ns = 0,
    .handle_type = DSO,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
    .loaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
   },
   {
    .name = "dlmopen-shared-unique:0:ns0-nsXp--ns0-nsXp",
    .desc = "dlmopen RTLD_SHARED a DF_GNU_1_UNIQUE dso into ns0 already in ns0 and proxied in nsX",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = LM_ID_BASE,
    .args.flags = RTLD_SHARED,
    .handle_ns = 0,
    .handle_type = DSO,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
    .loaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
   },
   {
    .name = "dlmopen-unique:0:ns0-nsXp--ns0-nsXp",
    .desc = "dlmopen a DF_GNU_1_UNIQUE dso into ns0 already in ns0 and proxied in nsX",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = EXPECTED_NS,
    .handle_ns = EXPECTED_NS,
    .handle_type = PROXY,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
    .loaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
   },
   {
    .name = "dlmopen-unique:0:ns0-nsXp--ns0-nsXp",
    .desc = "dlmopen RTLD_SHARED a DF_GNU_1_UNIQUE dso into ns0 already in ns0 and proxied in nsX",
    .args.dso_path = DSO_UNIQUE,
    .args.ns = EXPECTED_NS,
    .args.flags = RTLD_SHARED,
    .handle_ns = EXPECTED_NS,
    .handle_type = PROXY,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
    .loaded = { [0] = DSO, [EXPECTED_NS] = PROXY },
   },
  };
