static dlmopen_test_spec dltest[] =
  {
   {
    .name = "dlmopen:0:none--ns0",
    .desc = "dlmopen as dlopen",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_BASE,
    .loaded = { [0] = DSO|NEW },
    .handle_type = DSO,
    .handle_ns = LM_ID_BASE,
   },
   {
    .name = "dlmopen:0:ns0--ns0",
    .desc = "dlmopen a preloaded DSO in the base NS",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_BASE,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO },
    .handle_type = DSO,
    .handle_ns = LM_ID_BASE,
   },
   {
    .name = "dlmopen-shared:0:ns0--ns0",
    .desc = "dlmopen a preloaded DSO in the base NS with RTLD_SHARED",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_BASE,
    .args.flags = RTLD_SHARED,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO },
    .handle_type = DSO,
    .handle_ns = LM_ID_BASE,
   },
   {
    .name = "dlmopen:0:ns0--nsX",
    .desc = "dlmopen a preloaded DSO in the base NS into a new NS",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_NEWLM,
    .preloaded = { [0] = DSO },
    .loaded = { [0] = DSO, [EXPECTED_NS] = DSO|NEW },
    .handle_type = DSO,
    .handle_ns = EXPECTED_NS,
   },
   {
    .name = "dlmopen:0:ns0-nsX--ns0-nsX",
    .desc = "dlmopen a preloaded DSO in the base & secondary NS into the base NS",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_BASE,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = DSO },
    .loaded = { [0] = DSO, [EXPECTED_NS] = DSO },
    .handle_type = DSO,
    .handle_ns = LM_ID_BASE,
   },
   {
    .name = "dlmopen-shared:0:ns0-nsX--ns0-nsX",
    .desc = "dlmopen a preloaded DSO in the base & secondary NS into the base NS",
    .args.dso_path = DSO_NORMAL,
    .args.ns = LM_ID_BASE,
    .args.flags = RTLD_SHARED,
    .preloaded = { [0] = DSO, [EXPECTED_NS] = DSO },
    .loaded = { [0] = DSO, [EXPECTED_NS] = DSO },
    .handle_type = DSO,
    .handle_ns = LM_ID_BASE,
   },
  };
